# -*- coding: utf-8 -*-
{
    'name': "Odoo集成钉钉-多公司版本",
    'summary': """支持多个钉钉企业到Odoo进行信息管理""",
    'description': """支持多个钉钉企业到Odoo进行信息管理""",
    'author': "XueFeng.Su",
    'website': "https://www.sxfblog.com",
    'category': 'dingtalk',
    'version': '12.1.2',
    'depends': ['base', 'hr', 'mail', 'auth_oauth', 'hr_attendance'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'data/default_callback_list.xml',
        'data/auth_oauth_data.xml',
        'data/ir_cron.xml',

        'views/assets.xml',
        'wizard/synchronous.xml',
        'wizard/callback_get.xml',
        'wizard/employee_roster.xml',
        'wizard/approval_template.xml',
        'wizard/hr_attendance.xml',
        'wizard/dingtalk_microapp.xml',

        'views/dingtalk_config.xml',
        'views/hr_department.xml',
        'views/hr_employee.xml',
        'views/res_partner.xml',
        'views/callback_manage.xml',
        'views/res_users.xml',
        'views/web_templates.xml',
        'views/employee_roster.xml',
        'views/approval_template.xml',
        'views/approval_record.xml',
        'views/approval_control.xml',
        'views/hr_attendance_result.xml',
        'views/hr_sign.xml',
        'views/dingtalk_message.xml',
        'views/dingtalk_chat.xml',
        'views/dingtalk_chat_robot.xml',
        'views/dingtalk_microapp.xml',
    ],
    'qweb': [
        'static/xml/*.xml',
    ],
    'price': 450,
    'currency': 'EUR',
    'images': [
        'static/description/icon.png',
        'static/description/index.jpg',
    ],
    'license': 'AGPL-3',
}
